export default {
    userStatusList:[
        {key:"0", value:'正常'},
        {key:"1", value:'冻结'}
    ],
    platFormTypeListAdd:[
        {key:"1", value:'android'},
        {key:"2",value:'ios'}
    ],
    islogList:[
        {key:"0", value:'不打印日志'},
        {key:"1",value:'打印日志'}
    ],
    isStatusList:[
        {key:"0", value:'正常'},
        {key:"1",value:'禁用'}
    ],
    thiroCallbackTypeList:[
        {key:"1", value:'get'},
        {key:"2",value:'post'},
        {key:"3", value:'数据流'},
        {key:"4", value:'post+第三方渠道服务器ip'},
        {key:"5", value:'header头获取第三方回调信息'},
        {key:"6", value:'get+数据流获取回调消息'},
        {key:"7",value:"以数据流形式传送字符串"}
    ],
    allstatuelist:[
        {key:"-1",value:'全部'},
        {key:"0",value:'未审核'},
        {key:"1",value:'审核未通过'},
        {key:"2",value:'审核通过'},
    ],
    allstatue:[
        {key:"0",value:"全部"},
        {key:"1",value:"进行中"},
        {key:"2",value:"未开始"},
        {key:"3",value:"已结束"}
    ],
    isyoukelist:[
        {key:"-1",value:"全部"},
        {key:"1",value:"游客"},
        {key:"2",value:"非游客"}
    ],
    ispaylist:[
        {key:"-1",value:"全部"},
        {key:"2",value:"充值"},
        {key:"1",value:"非充值"}
    ],
    userpayornopay:[
        {key:"0",value:"全部"},
        {key:"1",value:"免费"},
        {key:"2",value:"付费"}
    ],
    dayinfolist:[
        {key:"0",value:"全部"},
        {key:"1",value:"下午"},
        {key:"2",value:"上午"}
    ],
    userpayornopayAdd:[
        {key:"1",value:"免费"},
        {key:"2",value:"付费"}
    ],
    dayinfolistAdd:[
        {key:"1",value:"下午"},
        {key:"2",value:"上午"}
    ],
    examinstatuslist:[
        {key:"0",value:"全部状态"},
        {key:"1",value:"流量/话费兑换"},
        {key:"2",value:"外挂"},
        {key:"3",value:"其他"}
    ],
    examinstatuslistAdd:[
        {key:"1",value:"流量/话费兑换"},
        {key:"2",value:"外挂"},
        {key:"3",value:"其他"}
    ],
    isOpen:[
        {key:"1",value:"开启"},
        {key:"0",value:"关闭"}
    ],
    permissionTypelist:[
        {key:"0",value:"查看权限"},
        {key:"1",value:"页面权限"},
        {key:"2",value:"表内权限"},
        {key:"3",value:"行内权限"},
        {key:"4",value:"行内双击权限"}
    ],
    messageinfolist:[
        {key:"3",value:"全部"},
        {key:"2",value:"房间"},
        {key:"1",value:"游戏"},
        {key:"4",value:"聊天"}
    ],
    banbeninfolist:[
        {key:"0#",value:"不限制"},
        {key:"gt#",value:"大于"},
        {key:"gteq#",value:"大于等于"},
        {key:"lt#",value:"小于"},
        {key:"lteq#",value:"小于等于"},
        {key:"eq#",value:"等于"},
    ],
    servertypeList:[
        {key:"-2",value:"非比赛房间"},
        {key:'2',value:'比赛房间'}
    ],
    copyserverroomList:[
        {key:"1",value:"普通"},
        {key:"2",value:"比赛"},
        {key:"3",value:"付费"}
    ],
    qudaoxianzhiinfolist:[
        {key:"0#",value:"不限制"},
        {key:"in#",value:"包含"},
        {key:"ex#",value:"不包含"}
    ],
    activeQudaolist:[
        {key:"0",value:"未限定"},
        {key:"1",value:"仅包含"},
        {key:"2",value:"不包含"}
    ],
    versioninfolist:[
        {key:"0",value:"未限定"},
        {key:"g",value:"大于"},
        {key:"ge",value:"大于等于"},
        {key:"e",value:"等于"},
        {key:"le",value:"小于等于"},
        {key:"l",value:"小于"},
    ],
    qudaoLimitlist:[
        {key:"0",value:"未限定"},
        {key:"in",value:"仅包含"},
        {key:"ex",value:"不包含"}
    ],
    editionstatue:[
        {key:"-1",value:"全部"},
        {key:"0",value:"通用版本"},
        {key:"1",value:"大版本"},
        {key:"2",value:"指定版本"}
    ],
    downloadType:[
        {key:"ios",value:"ios"},
        {key:"android",value:"android"},
    ],
    qudaoTypeList:[
        {key:"1",value:"联运"},
        {key:"2",value:"CPS"},
    ],
    arealist:[
        {key:"1",value:"北区"},
        {key:"2",value:"南区"},
    ],
    platFormList:[
        {key:"-1",value:"选择类型"},
        {key:"1",value:"appstore"},
        {key:"2",value:"其他"}
    ],
    updatechannelType:[
        {key:"0",value:"不更新"},
        {key:"1",value:"非强制更新"},
        {key:"2",value:"强制更新"}
    ],
    updateaddChannelType:[
        {key:"0",value:"自动"},
        {key:"1",value:"跳转"},
    ],
    qudaosortList:[
        {key:"0",value:"安卓"},
        {key:"1",value:"IOS"},
    ],
    banbenTypeList:[
        {key:"0",value:"友盟统计版本"},
        {key:"1",value:"项目版本"},
    ],
    editionType:[
        {key:"0",value:"通用版本"},
        {key:"1",value:"大版本"},
        {key:"2",value:"指定版本"}
    ],
    emailTypelist:[
        {key:"-1",value:"全部"},
        {key:"0",value:"其他"},
        {key:"2",value:"活动"},
        {key:"3",value:"补偿"},
        {key:"4",value:"召回"},
    ],
    registertimeisshowlist:[
        {key:"-1",value:"关"},
        {key:"1",value:"可见"},
        {key:"0",value:"不可见"}
    ],
    pkMatchList:[
        {key:"1",value:"PK赛"},
        {key:"2",value:"定点赛"},
        {key:"3",value:"挑战赛"},
    ],
    pkMatchMoneyList:[
        {key:"1",value:"使用初始化金钱"},
        {key:"2",value:"使用幸运豆"},
    ],
    systemStatusInfoList:[
        {key:"",value:"全部"},
        {key:"0",value:"未指定"},
        {key:"1",value:"游戏功能开关"},
        {key:"2",value:"充值配置"},
    ],
    addSystemStatusInfoList:[
        {key:"0",value:"未指定"},
        {key:"1",value:"游戏功能开关"},
        {key:"2",value:"充值配置"},
    ],
    isPayFirstoList:[
        {key:"0",value:"不限制"},
        {key:"1",value:"需要完成首充才能参与"},
    ],
    payinfoList:[
        {key:"-1",value:"全部"},
        {key:"0",value:"未付款"},
        {key:"2",value:"付款成功"},
    ],
    allpayResultList:[
        {key:"-1",value:"请选类型"},
        {key:"1",value:"存款"},
        {key:"2",value:"取款"},
        {key:"3",value:"邀请获取"},
        {key:"4",value:"被邀请获取"},
        {key:"5",value:"封红包"},
        {key:"6",value:"拆红包"},
        {key:"7",value:"聊天扣费"},
        {key:"8",value:"土豪返利"},
        {key:"9",value:"排行榜自动发奖"},
        {key:"10",value:"系统奖励"},
        {key:"11",value:"赠送道具"},
        {key:"12",value:"奖券兑豆"},
        {key:"13",value:"vip领取"},
        {key:"121",value:"签到"},
        {key:"134",value:"充值"},
        {key:"135",value:"补单"},
        {key:"300",value:"登陆领奖"},
        {key:"666",value:"绑定手机"},
        {key:"667",value:"绑定邮箱"},
        {key:"669",value:"抢购活动"},
        {key:"700",value:"赠送"}
    ],
    showtypelist:[
        {key:"0",value:"全显示"},
        {key:"1",value:"手机游戏商城显示"},
        {key:"2",value:"微信商城显示"},
        {key:"3",value:"游戏商城内页显示"},
    ],
    shopStatusList:[
        {key:"0", value:'正常'},
        {key:"1", value:'禁用'}
    ],
    shopDiscountList:[
        {key:"1", value:'是'},
        {key:"0", value:'否'}
    ],
    deliveryStatuslist:[
        {key:"-1",value:"发货状态"},
        {key:"0",value:"未发货"},
        {key:"2",value:"已发货"},
        {key:"3",value:"已撤销"},
        {key:"13",value:"备注不为空"},
    ],
    shopTypelist:[
        {key:"-1",value:"商品类型"},
        {key:"1",value:"话费"},
        {key:"2",value:"实物"},
        {key:"3",value:"京东卡"},
        {key:"4",value:"流量"},
        {key:"5",value:"道具"},
        {key:"6",value:"台历"},
        {key:"7",value:"生活用品"},
        {key:"8",value:"游戏周边"},
        {key:"9",value:"其他"},
        {key:"10",value:"电子卡券"},
    ],
    consumeTypelist:[
        {key:"",value:"消耗类型"},
        {key:"0",value:"奖券"},
        {key:"1",value:"道具"},
        {key:"2",value:"水晶"},
    ],
    sealIplist:[
        {key:"1",value:"封IP"},
        {key:"2",value:"封MAC"},
    ],
    festivalPrizeTypelist:[
        {key:"",value:"方式"},
        {key:"use",value:"使用"},
        {key:"get",value:"获取"},
        {key:"sell",value:"出售"},
        {key:"compose",value:"合成"},
    ],
    praiseTypelist:[
        {key:"-1",value:"点赞类型"},
        {key:"0",value:"捕鱼达人"},
        {key:"1",value:"奖券达人"},
        {key:"2",value:"在线时长达人"},
        {key:"3",value:"明日之星"},
        {key:"4",value:"土豪榜"},
    ],
    dropTypelist:[
        {key:"",value:"掉落类型"},
        {key:"1",value:"击杀"},
        {key:"2",value:"击中"},
    ],
    allWarheadTypelist:[
        {key:"",value:"所有弹头"},
        {key:"100265",value:"青铜弹头"},
        {key:"100266",value:"白银弹头"},
        {key:"100267",value:"黄金弹头"},
        {key:"100268",value:"白金弹头"},
        {key:"100269",value:"核弹"},
    ],
    scoreTypelist:[
        {key:"-1",value:"幸运豆"},
        {key:"100168",value:"水晶"},
        {key:"100265",value:"青铜弹头"},
        {key:"100266",value:"白银弹头"},
        {key:"100267",value:"黄金弹头"},
        {key:"100268",value:"白金弹头"}
    ],
    checkTypelist:[
        {key:"",value:"类型"},
        {key:"1",value:"对方的sdk"},
        {key:"2",value:"官方sdk"},
        {key:"3",value:"三网支付"},
        {key:"4",value:"苹果商店"},
    ],
    roomTypelist:[
        {key:"",value:"全部"},
        {key:"新手房",value:"新手房"},
        {key:"百炮房",value:"百炮房"},
        {key:"千炮房",value:"千炮房"},
        {key:"万炮房",value:"万炮房"},
    ],
    gameRecordSelect:[
        {key:"-1",value:"选择功能"},
        {key:"1",value:"比赛记录"},
        {key:"2",value:"报名记录"},
    ],
    fishMasterTypelist:[
        {key:"-1",value:"全部"},
        {key:"0",value:"捕鱼达人"},
        {key:"1",value:"奖券达人"},
        {key:"2",value:"在线时长达人"},
        {key:"3",value:"明日之星"},
        {key:"4",value:"土豪榜"},
        {key:"5",value:"道具达人"},
    ],
    propTypelist:[
        {key:"",value:"方式"},
        {key:"use",value:"使用"},
        {key:"get",value:"获取"},
        {key:"sell",value:"出售"},
        {key:"compose",value:"合成"},
        {key:"useInGame",value:"游戏内使用"},
    ],
    shareScoreTypelist:[
      {key:"-1",value:"请选择类型"},
      {key:"0",value:"被邀请用户得分"},
      {key:"1",value:"邀请用户得分"},
      {key:"2",value:"成功发送一次邀请码"},
      {key:"3",value:"分享到QQ空间"},
      {key:"4",value:"分享到朋友圈"},
      {key:"5",value:"累计分享次数"},
    ],
    spreaderTypelist:[
      {key:"-1",value:"全渠道"},
      {key:"1",value:"ios"},
      {key:"2",value:"android"},
    ],
    operaeditTypelist:[
        {key:"-1",value:"密码类型"},
        {key:"1",value:"登录密码"},
        {key:"2",value:"银行密码"},
    ],
    operaReleaseOfTitleTypelist:[
        {key:"-1",value:"类型"},
        {key:"1",value:"冻结"},
        {key:"0",value:"解冻"},
    ],
    operaBindTypelist:[
        {key:"-1",value:"类型"},
        {key:"1",value:"绑定"},
        {key:"2",value:"解绑"},
    ],
    operaCheckFaceTypelist:[
        {key:"-1",value:"类型"},
        {key:"1",value:"不通过"},
        {key:"2",value:"通过"},
    ],
    operaJinyanTypelist:[
        {key:"-1",value:"类型"},
        {key:"1",value:"禁言"},
        {key:"0",value:"解除禁言"},
    ],
    userLtvTypelist:[
        {key:"0",value:"LTV"},
        {key:"1",value:"充值人数"},
        {key:"2",value:"充值金额"},
    ],
    userLtvChannelTypelist:[
        {key:"0",value:"所有渠道"},
        {key:"1",value:"指定渠道"},
        {key:"-1",value:"排除渠道"},
    ],
    isSpreaderList:[
        {key:"0", value:'管理员'},
        {key:"1", value:'渠道管理员'},
        {key:"2",value:'外放渠道管理员'}
    ],
    activeList:[
        {key:"-1", value:'龙宫夺宝'},
        {key:"-2", value:'新版龙宫夺宝'},
        {key:"230",value:'弹头冲冲冲'},
        {key:"216", value:'许愿活动'},
        {key:"240_1", value:'深海游乐场摇骰子'},
        {key:"240_2",value:'深海游乐场颁奖'},
        {key:"224_1",value:'敲敲乐领奖'},
        {key:"224_2",value:'敲敲乐任务'},
        {key:"224_3",value:'敲敲乐游戏'},
        {key:"238",value:'摇钱树'},
    ]
}
